apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nlmp1noc2-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap-docker/rhtap-qe-hbqc:cecae50ad000ed7e966d91a570996046244aee73@sha256:0cc2adc3585c6b197218861eefec044ea71d072b3c5c610fa8841042809ea573
          name: container-image
